app:
  subject_id: "42"

paths:
  # Use forward slashes or absolute Windows paths
  data_dir: "data"
  result_dir: "data/results"
  question_lib_filename: "data/libs/question_lib_v4.json"
  report_file: "data/results/Report_${subject_id}.csv"
  notes_file: "data/results/Notes_${subject_id}.csv"
  logs_dir: "data/logs"
  record_csv: "data/record.csv"

rl:
  item_n_states: 38
  epsilon: 0.9
  alpha: 0.1
  gamma: 0.9
  # item_importance: [0, 5, 4, 4, 2, 5, 2, 2, 1, 3, 4, 3, 1, 4, 2, 4, 3, 1, 4, 4]
  # number_questions: [0, 4, 1, 2, 2, 5, 1, 1, 1, 2, 3, 2, 1, 1, 3, 2, 1, 3, 1, 1]
  item_importance: [0, 5, 5, 5, 5, 4, 4, 4, 2, 2, 5, 5, 5, 5, 5, 2, 2, 1, 3, 3, 4, 4, 4, 3, 3, 1, 4, 2, 2, 2, 4, 4, 3, 1, 1, 1, 4, 4]
  number_questions: [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
 

openai:
  base_url: "https://us.api.openai.com/v1"
  model: "gpt-5"
  temperature: 0.7
  max_tokens: 400
