subject_id: "8901"

# Paths (optional overrides). Use forward slashes or absolute Windows paths.
# data_dir: "Subject_8899_Mobicom_SenSys"
# result_dir: "Subject_8899_Mobicom_SenSys/data_collection_results"
# question_lib_filename: "Subject_8899_Mobicom_SenSys/question_lib_v3_8901.json"
# report_file: "Subject_8899_Mobicom_SenSys/data_collection_results/Report_8901.csv"
# notes_file: "Subject_8899_Mobicom_SenSys/data_collection_results/Notes_8901.csv"
# record_csv: "Subject_8899_Mobicom_SenSys/record.csv"

# RL hyperparameters
item_n_states: 20
epsilon: 0.9
alpha: 0.1
gamma: 0.9

# Importance weights per item index
item_importance: [0, 5, 4, 4, 2, 5, 2, 2, 1, 3, 4, 3, 1, 4, 2, 4, 3, 1, 4, 4]

# Number of questions per item index
number_questions: [0, 4, 1, 2, 2, 5, 1, 1, 1, 2, 3, 2, 1, 1, 3, 2, 1, 3, 1, 1]
