name: LLM_therapist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.21.0
  - pandas>=1.3.0
  - flask>=2.0.0
  - requests>=2.25.0
  - tqdm>=4.64.0
  - coloredlogs>=15.0
  - pip
  - pyyaml>=6.0.0
  - pip:
    - openai>=1.07.3
    - flask-cors>=3.0.0
    - word2number>=1.1