name: LLM_therapist
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.136
  - blas-devel=3.9.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - click=8.3.0
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - exceptiongroup=1.3.0
  - expat=2.7.1
  - flask=3.1.2
  - h2=4.3.0
  - hpack=4.1.0
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - iniconfig=2.0.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.1
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libopenblas=0.3.30
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - llvm-openmp=21.1.0
  - markupsafe=3.0.2
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openblas=0.3.30
  - openssl=3.5.3
  - packaging=25.0
  - pandas=2.3.2
  - pip=25.2
  - pluggy=1.6.0
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - readline=8.2
  - requests=2.32.5
  - setuptools=72.1.0
  - six=1.17.0
  - sqlite=3.50.2
  - tk=8.6.15
  - tomli=2.2.1
  - tqdm=4.67.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - distro==1.9.0
      - flask-cors==6.0.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jiter==0.11.0
      - openai==1.07.3
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyyaml==6.0.2
      - sniffio==1.3.1
      - typing-inspection==0.4.1
      - word2number==1.1
